### ISSUE TITLE
License the software

### ISSUE THREAD

**Issue by ns-rse** [TheLostLambda/smithereens#1]
Currently there is no license applied to the code in this repository and so by default it falls under closed copyright.

It would be useful if the code is openly licensed and aligns with other components of PGFinder which has the [GNU GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) license applied.

Guidelines on applying it are : [How to Use GNU Licenses for Your Own Software - GNU Project - Free Software Foundation](https://www.gnu.org/licenses/gpl-howto.html)

**Comment by TheLostLambda** [comment]
I've added an AGPL license now! It should be perfectly compatible with the GPL in PGFinder!
